- hosts: dev
  become: yes
  gather_facts: no
  tasks:
    - name: Install Rsyslog
      apt:
        name: rsyslog
        state: present
        update_cache: true
    
    - name: Install Logrotate
      apt:
        name: logrotate
        state: present
        update_cache: true

    - name: Update Rsyslog configuration
      lineinfile:
        dest: /etc/rsyslog.conf
        line: "{{ item }}"
      with_items:
        - '$ModLoad imudp \n' #UDP enable
        - '$UDPServerRun 514 \n' 
        - '$ModLoad imtcp \n' #TCP enable
        - '$TCPServerRun 514 \n' 
        - '$template AgentLogs, "/var/log/agentlogs/%FROMHOST-IP%/%PROGRAMNAME%.log" \n'
        - '*.* ?AgentLogs \n'

    - name: Restart Rsyslog
      service:
        name: rsyslog
        state: restarted   



        