- hosts: syslog-dev
  become: yes
  tasks:
    - name: install rsyslog
      apt:
        name: rsyslog
        state: present
        update_cache: true
    - name: install logrotate
      apt:
        name: logrotate
        state: present
        update_cache: true

        