- hosts: dev
  become: yes
  gather_facts: no
  tasks:
    - name: Rsyslog installation
      apt:
        name: rsyslog
        state: present
        update_cache: true

    - name: Logrotate installation
      apt:
        name: logrotate
        state: present
        update_cache: true
    
    - name: Rsyslog application settings
      lineinfile:
        dest: /etc/rsyslog.conf
        regexp: '^#?\s*{{ item }}\s'
        line: "{{ item }}"
      with_items:
        - '$ModLoad imudp' #UDP enable
        - '$UDPServerRun 514' 
        - '$ModLoad imtcp' #TCP enable
        - '$InputTCPServerRun 514' 
        - '$template AgentLogs, "/var/log/agentlogs/%FROMHOST-IP%/%PROGRAMNAME%.log"'
        - '*.* ?AgentLogs'
      notify: Restart rsyslog

  handlers:
  - name: Restart rsyslog
    service: 
      name: rsyslog
      state: restarted