- hosts: dev
  become: yes
  gather_facts: no
  tasks:
    - name: Install rsyslog
      apt:
        name: rsyslog
        state: present
        update_cache: true
    
    - name: Install logrotate
      apt:
        name: logrotate
        state: present
        update_cache: true

        